window.BANK = (window.BANK || []).concat(
[
  {
    "id": "py-bank-account-oop",
    "section": "python",
    "type": "python",
    "topic": "OOP: classes, inheritance, custom exceptions",
    "title": "Bank accounts with an overdraft rule",
    "prompt": [
      "Implement three classes.",
      "",
      "**`InsufficientFundsError`**: a custom exception that subclasses `Exception`.",
      "",
      "**`BankAccount(owner, balance=0)`**",
      "- `balance` attribute holds the current balance.",
      "- `deposit(amount)`: adds `amount`. Raise `ValueError` if `amount <= 0`.",
      "- `withdraw(amount)`: subtracts `amount`. Raise `ValueError` if `amount <= 0`. If `amount` is more than the balance, raise `InsufficientFundsError` with the message `Insufficient funds: balance B, requested A` (B and A shown exactly as Python prints them) and leave the balance unchanged. Withdrawing the entire balance is allowed.",
      "",
      "**`SavingsAccount(owner, balance=0, min_balance=100)`**: a subclass of `BankAccount`. A withdrawal must leave at least `min_balance` in the account; otherwise raise `InsufficientFundsError` (any message) and leave the balance unchanged."
    ],
    "starter": [
      "class InsufficientFundsError(Exception):",
      "    pass",
      "",
      "",
      "class BankAccount:",
      "    def __init__(self, owner, balance=0):",
      "        pass",
      "",
      "    def deposit(self, amount):",
      "        pass",
      "",
      "    def withdraw(self, amount):",
      "        pass",
      "",
      "",
      "class SavingsAccount(BankAccount):",
      "    def __init__(self, owner, balance=0, min_balance=100):",
      "        pass",
      "",
      "    def withdraw(self, amount):",
      "        pass",
      ""
    ],
    "solution": [
      "class InsufficientFundsError(Exception):",
      "    pass",
      "",
      "",
      "class BankAccount:",
      "    def __init__(self, owner, balance=0):",
      "        self.owner = owner",
      "        self.balance = balance",
      "",
      "    def deposit(self, amount):",
      "        if amount <= 0:",
      "            raise ValueError(\"Deposit must be positive\")",
      "        self.balance += amount",
      "",
      "    def withdraw(self, amount):",
      "        if amount <= 0:",
      "            raise ValueError(\"Withdrawal must be positive\")",
      "        if amount > self.balance:",
      "            raise InsufficientFundsError(",
      "                f\"Insufficient funds: balance {self.balance}, requested {amount}\"",
      "            )",
      "        self.balance -= amount",
      "",
      "",
      "class SavingsAccount(BankAccount):",
      "    def __init__(self, owner, balance=0, min_balance=100):",
      "        super().__init__(owner, balance)",
      "        self.min_balance = min_balance",
      "",
      "    def withdraw(self, amount):",
      "        if amount > 0 and self.balance - amount < self.min_balance:",
      "            raise InsufficientFundsError(",
      "                f\"Withdrawal would leave less than {self.min_balance}\"",
      "            )",
      "        super().withdraw(amount)",
      ""
    ],
    "tests": [
      { "name": "Deposit adds to the balance", "setup": "a = BankAccount('Ana', 50)\na.deposit(25)", "expr": "a.balance", "expect": "75" },
      { "name": "Withdrawing the whole balance leaves 0", "setup": "a = BankAccount('Ana', 40)\na.withdraw(40)", "expr": "a.balance", "expect": "0" },
      { "name": "Overdrawing raises InsufficientFundsError", "setup": "a = BankAccount('Ana', 40)", "expr": "a.withdraw(40.01)", "raises": "InsufficientFundsError" },
      { "name": "Zero deposit raises ValueError", "setup": "a = BankAccount('Ana')", "expr": "a.deposit(0)", "raises": "ValueError" },
      { "name": "Error message format, balance unchanged", "setup": "a = BankAccount('Ana', 40)\ntry:\n    a.withdraw(50)\n    msg = None\nexcept InsufficientFundsError as e:\n    msg = str(e)", "expr": "(msg, a.balance)", "expect": "('Insufficient funds: balance 40, requested 50', 40)" },
      { "name": "Savings keeps the minimum balance", "setup": "s = SavingsAccount('Bo', 300)\ns.withdraw(200)", "expr": "s.withdraw(0.01)", "raises": "InsufficientFundsError" }
    ],
    "approach": [
      "Start with the exception: class InsufficientFundsError(Exception): pass. Raising it with a message makes str(e) return that message.",
      "Validate first, mutate last. Check every error condition before changing self.balance, so a failed withdrawal leaves the balance untouched.",
      "Read the boundary words: \"more than the balance\" is >, so withdrawing exactly the balance is allowed.",
      "In the subclass, call super().__init__ to reuse the parent's setup, and override only withdraw. Do the extra minimum-balance check, then hand off to super().withdraw for the normal rules.",
      "Build the message with an f-string so numbers print the way Python prints them (40, not 40.0)."
    ],
    "mistakes": [
      "Using >= instead of > for the overdraft check, which wrongly blocks withdrawing the exact balance.",
      "Subtracting before checking, so a failed withdrawal still changes the balance.",
      "Forgetting super().__init__ in SavingsAccount, so self.balance never exists (AttributeError).",
      "Returning an error string instead of raising the exception.",
      "Subclassing ValueError or BaseException when the prompt says Exception, or misspelling the class name the tests import."
    ]
  },
  {
    "id": "py-mask-card",
    "section": "python",
    "type": "python",
    "topic": "String manipulation with edge cases",
    "title": "Mask a card number",
    "prompt": [
      "Write `mask_card(card)`. `card` is a string of digits that may contain spaces or dashes as separators.",
      "",
      "Return the string with every digit except the **last four digits** replaced by `*`. Separators stay exactly where they are. If the string has 4 or fewer digits, return it unchanged (this includes the empty string).",
      "",
      "Examples:",
      "- `mask_card(\"4111 1111 1111 1234\")` returns `\"**** **** **** 1234\"`",
      "- `mask_card(\"12 34 5\")` returns `\"*2 34 5\"`"
    ],
    "starter": [
      "def mask_card(card):",
      "    pass",
      ""
    ],
    "solution": [
      "def mask_card(card):",
      "    to_mask = sum(ch.isdigit() for ch in card) - 4",
      "    out = []",
      "    for ch in card:",
      "        if ch.isdigit() and to_mask > 0:",
      "            out.append('*')",
      "            to_mask -= 1",
      "        else:",
      "            out.append(ch)",
      "    return ''.join(out)",
      ""
    ],
    "tests": [
      { "name": "Spaces kept", "expr": "mask_card('4111 1111 1111 1234')", "expect": "'**** **** **** 1234'" },
      { "name": "Dashes kept", "expr": "mask_card('4111-1111-1111-1234')", "expect": "'****-****-****-1234'" },
      { "name": "Exactly four digits is unchanged", "expr": "mask_card('1234')", "expect": "'1234'" },
      { "name": "Five digits masks one", "expr": "mask_card('12345')", "expect": "'*2345'" },
      { "name": "Empty string", "expr": "mask_card('')", "expect": "''" },
      { "name": "Last four digits span separators", "expr": "mask_card('12 34 5')", "expect": "'*2 34 5'" }
    ],
    "approach": [
      "Count the digits first, so you know how many to hide: total digits minus 4.",
      "Walk the string once. Replace a digit with * while you still have digits left to hide; copy everything else unchanged.",
      "Build a list and ''.join it at the end instead of slicing, because separators make positions and digit counts differ.",
      "Test the boundaries in your head: 4 digits (nothing to hide), 0 digits (empty string), and separators inside the last four."
    ],
    "mistakes": [
      "Slicing the last 4 characters (card[-4:]) instead of the last 4 digits: '12 34 5' would keep ' 5' plus two digits and get the count wrong.",
      "Removing the separators, or masking them too.",
      "Masking when there are exactly 4 digits, or crashing on the empty string.",
      "Returning None by forgetting the return statement, or printing the result instead of returning it."
    ]
  },
  {
    "id": "py-rank-customers",
    "section": "python",
    "type": "python",
    "topic": "Sorting with lambdas and tie-breaks",
    "title": "Rank customers for a credit offer",
    "prompt": [
      "Write `rank_customers(customers)`. Each customer is a tuple `(name, credit_score, balance)`. Some customers have no credit score yet: their `credit_score` is `None`.",
      "",
      "Return a list of **names** of customers who have a credit score, ordered by:",
      "- `credit_score`, highest first",
      "- then `balance`, highest first",
      "- then `name`, alphabetically",
      "",
      "An empty input returns an empty list."
    ],
    "starter": [
      "def rank_customers(customers):",
      "    pass",
      ""
    ],
    "solution": [
      "def rank_customers(customers):",
      "    scored = [c for c in customers if c[1] is not None]",
      "    scored.sort(key=lambda c: (-c[1], -c[2], c[0]))",
      "    return [name for name, _, _ in scored]",
      ""
    ],
    "tests": [
      { "name": "Higher score first", "expr": "rank_customers([('Ana', 700, 100), ('Bo', 750, 50)])", "expect": "['Bo', 'Ana']" },
      { "name": "Score tie broken by balance", "expr": "rank_customers([('Ana', 700, 100), ('Bo', 700, 900)])", "expect": "['Bo', 'Ana']" },
      { "name": "Score and balance tie broken by name", "expr": "rank_customers([('Cy', 700, 500), ('Ana', 700, 500), ('Bo', 680, 999)])", "expect": "['Ana', 'Cy', 'Bo']" },
      { "name": "Customers without a score are left out", "expr": "rank_customers([('Ana', None, 5000), ('Bo', 600, 10)])", "expect": "['Bo']" },
      { "name": "Empty list", "expr": "rank_customers([])", "expect": "[]" },
      { "name": "Nobody has a score", "expr": "rank_customers([('Ana', None, 1), ('Bo', None, 2)])", "expect": "[]" }
    ],
    "approach": [
      "Filter first: drop the None scores before sorting, because comparing None with a number raises TypeError in Python 3.",
      "Sort with one key that returns a tuple. Tuples compare element by element, so (score, balance, name) handles every tie-break in one pass.",
      "To sort a number highest first inside an otherwise ascending sort, negate it: -score. Names stay ascending.",
      "Return just the names, and check the empty input returns [] rather than None."
    ],
    "mistakes": [
      "Sorting with reverse=True and a (score, balance, name) key: it also reverses the names, so ties come out Z to A.",
      "Not filtering None, which raises TypeError: '<' not supported between 'NoneType' and 'int'.",
      "Returning the whole tuples instead of just the names.",
      "Sorting three separate times in the wrong order. Stable multi-pass sorting works only if you sort by the least important key first."
    ]
  },
  {
    "id": "py-parse-amount",
    "section": "python",
    "type": "python",
    "topic": "String parsing and exceptions",
    "title": "Parse a money amount",
    "prompt": [
      "Statements show amounts as text. Write `parse_amount(text)` that returns the amount as a `float`.",
      "",
      "Accepted formats, with optional whitespace around the whole string:",
      "- Digits with an optional decimal part: `7`, `45.00`",
      "- An optional `$` before the digits: `$12.50`",
      "- Commas as thousands separators, in the right places: `$1,234.50`",
      "- A negative amount written with a leading `-` (`-$20`) or in parentheses (`(45.00)`)",
      "",
      "For anything else, including an empty string, raise `ValueError`."
    ],
    "starter": [
      "def parse_amount(text):",
      "    pass",
      ""
    ],
    "solution": [
      "import re",
      "",
      "NUMBER = re.compile(r'\\d{1,3}(,\\d{3})+(\\.\\d+)?|\\d+(\\.\\d+)?')",
      "",
      "",
      "def parse_amount(text):",
      "    s = text.strip()",
      "    negative = False",
      "    if s.startswith('(') and s.endswith(')'):",
      "        negative, s = True, s[1:-1].strip()",
      "    elif s.startswith('-'):",
      "        negative, s = True, s[1:].strip()",
      "    if s.startswith('$'):",
      "        s = s[1:]",
      "    if not NUMBER.fullmatch(s):",
      "        raise ValueError(f'Invalid amount: {text!r}')",
      "    value = float(s.replace(',', ''))",
      "    return -value if negative else value",
      ""
    ],
    "tests": [
      { "name": "Dollar sign and thousands comma", "expr": "parse_amount('$1,234.50')", "expect": "1234.5" },
      { "name": "Leading minus", "expr": "parse_amount('-$20')", "expect": "-20.0" },
      { "name": "Parentheses mean negative", "expr": "parse_amount('(45.00)')", "expect": "-45.0" },
      { "name": "Surrounding whitespace", "expr": "parse_amount('  7 ')", "expect": "7.0" },
      { "name": "Empty string raises ValueError", "expr": "parse_amount('')", "raises": "ValueError" },
      { "name": "Misplaced comma raises ValueError", "expr": "parse_amount('1,23')", "raises": "ValueError" }
    ],
    "approach": [
      "Peel the string from the outside in: strip whitespace, detect and remove the negative marker, remove the $, then validate what's left.",
      "Validate before converting. float() accepts things you don't want (like 'nan' or '1e5') and rejects commas, so check the shape first, here with a regular expression.",
      "Let the empty-string case fall through to the same ValueError instead of special-casing it.",
      "Raise ValueError yourself with a clear message; don't return None or a sentinel."
    ],
    "mistakes": [
      "Removing every comma before validating, so '1,23' wrongly parses as 123.",
      "Calling float() on the raw text, which fails on '$' and ',' and accepts 'nan'.",
      "Forgetting the parentheses form of negative numbers.",
      "Catching the ValueError and returning None or 0, so the test expecting an exception fails."
    ]
  },
  {
    "id": "py-loan-classes",
    "section": "python",
    "type": "python",
    "topic": "OOP: inheritance, method overriding, __str__",
    "title": "Loans with a promotional period",
    "prompt": [
      "Implement two classes.",
      "",
      "**`Loan(borrower, principal, annual_rate)`**",
      "- Raise `ValueError` if `principal <= 0` or `annual_rate < 0`.",
      "- `interest(months)` returns simple interest, `principal × annual_rate × months / 12`, rounded to 2 decimals. Raise `ValueError` if `months < 0`. Zero months gives `0.0`.",
      "- `str(loan)` returns `Borrower: $principal at rate%`, with the principal using thousands separators and 2 decimals, and the rate as a percentage with 2 decimals. Example: `Ana: $12,500.00 at 4.50%`",
      "",
      "**`PromoLoan(borrower, principal, annual_rate, promo_months)`**: a subclass of `Loan`. No interest is charged during the first `promo_months` months, so `interest(months)` charges only the months after the promotion. `str()` adds ` (promo N months)` to the end of the parent's text."
    ],
    "starter": [
      "class Loan:",
      "    def __init__(self, borrower, principal, annual_rate):",
      "        pass",
      "",
      "    def interest(self, months):",
      "        pass",
      "",
      "    def __str__(self):",
      "        pass",
      "",
      "",
      "class PromoLoan(Loan):",
      "    def __init__(self, borrower, principal, annual_rate, promo_months):",
      "        pass",
      "",
      "    def interest(self, months):",
      "        pass",
      "",
      "    def __str__(self):",
      "        pass",
      ""
    ],
    "solution": [
      "class Loan:",
      "    def __init__(self, borrower, principal, annual_rate):",
      "        if principal <= 0:",
      "            raise ValueError('principal must be positive')",
      "        if annual_rate < 0:",
      "            raise ValueError('annual_rate cannot be negative')",
      "        self.borrower = borrower",
      "        self.principal = principal",
      "        self.annual_rate = annual_rate",
      "",
      "    def interest(self, months):",
      "        if months < 0:",
      "            raise ValueError('months cannot be negative')",
      "        return round(self.principal * self.annual_rate * months / 12, 2)",
      "",
      "    def __str__(self):",
      "        return f'{self.borrower}: ${self.principal:,.2f} at {self.annual_rate * 100:.2f}%'",
      "",
      "",
      "class PromoLoan(Loan):",
      "    def __init__(self, borrower, principal, annual_rate, promo_months):",
      "        super().__init__(borrower, principal, annual_rate)",
      "        self.promo_months = promo_months",
      "",
      "    def interest(self, months):",
      "        if months < 0:",
      "            raise ValueError('months cannot be negative')",
      "        return super().interest(max(0, months - self.promo_months))",
      "",
      "    def __str__(self):",
      "        return f'{super().__str__()} (promo {self.promo_months} months)'",
      ""
    ],
    "tests": [
      { "name": "Simple interest for 6 months", "expr": "Loan('Ana', 12000, 0.05).interest(6)", "expect": "300.0" },
      { "name": "Zero months is zero interest", "expr": "Loan('Ana', 1000, 0.07).interest(0)", "expect": "0.0" },
      { "name": "String format", "expr": "str(Loan('Ana', 12500, 0.045))", "expect": "'Ana: $12,500.00 at 4.50%'" },
      { "name": "Zero principal raises ValueError", "expr": "Loan('Bo', 0, 0.05)", "raises": "ValueError" },
      { "name": "Promo months are free, later months are charged", "setup": "p = PromoLoan('Cy', 12000, 0.06, 3)", "expr": "(p.interest(2), p.interest(5))", "expect": "(0.0, 120.0)" },
      { "name": "Promo string extends the parent's", "expr": "str(PromoLoan('Cy', 12000, 0.06, 3))", "expect": "'Cy: $12,000.00 at 6.00% (promo 3 months)'" }
    ],
    "approach": [
      "Validate in __init__ and raise immediately, before storing anything.",
      "Use format specs for output: {x:,.2f} gives thousands separators and 2 decimals; multiply the rate by 100 for a percentage.",
      "In the subclass, reuse the parent: super().__init__ for setup, super().interest for the formula, super().__str__ for the text. Override only what changes.",
      "Handle the boundary where months is less than the promotion: max(0, months − promo) keeps it from going negative."
    ],
    "mistakes": [
      "Formatting with str(principal), which gives '12500' instead of '12,500.00'.",
      "Rounding the rate or principal instead of the final interest.",
      "Copying the parent's formula into the subclass instead of calling super(), then forgetting to round there.",
      "Charging negative interest when months < promo_months.",
      "Printing the text inside __str__ instead of returning it, so str() raises TypeError: __str__ returned non-string."
    ]
  },
  {
    "id": "py-monthly-totals",
    "section": "python",
    "type": "python",
    "topic": "Dictionaries, string slicing and rounding",
    "title": "Monthly spending totals",
    "prompt": [
      "Write `monthly_totals(transactions)`. Each transaction is a dict like `{'date': '2025-01-15', 'amount': 42.5}`. An `amount` of `None` means the transaction was voided.",
      "",
      "Return a dict that maps each month (`'YYYY-MM'`) to the total amount for that month, rounded to 2 decimals. Voided transactions add nothing, but a month whose transactions are all voided still appears with `0.0`. The dict's keys must be in ascending month order. An empty list returns `{}`."
    ],
    "starter": [
      "def monthly_totals(transactions):",
      "    pass",
      ""
    ],
    "solution": [
      "def monthly_totals(transactions):",
      "    totals = {}",
      "    for t in transactions:",
      "        month = t['date'][:7]",
      "        totals.setdefault(month, 0.0)",
      "        if t['amount'] is not None:",
      "            totals[month] += t['amount']",
      "    return {month: round(totals[month], 2) for month in sorted(totals)}",
      ""
    ],
    "tests": [
      { "name": "Two months", "expr": "monthly_totals([{'date': '2025-01-03', 'amount': 10.0}, {'date': '2025-01-20', 'amount': 5.5}, {'date': '2025-02-01', 'amount': 7.0}])", "expect": "{'2025-01': 15.5, '2025-02': 7.0}" },
      { "name": "Rounded to 2 decimals", "expr": "monthly_totals([{'date': '2025-03-01', 'amount': 0.1}, {'date': '2025-03-02', 'amount': 0.2}])", "expect": "{'2025-03': 0.3}" },
      { "name": "Voided amounts are skipped", "expr": "monthly_totals([{'date': '2025-04-01', 'amount': None}, {'date': '2025-04-09', 'amount': 20.0}])", "expect": "{'2025-04': 20.0}" },
      { "name": "Month with only voided transactions shows 0.0", "expr": "monthly_totals([{'date': '2025-05-05', 'amount': None}])", "expect": "{'2025-05': 0.0}" },
      { "name": "Empty input", "expr": "monthly_totals([])", "expect": "{}" },
      { "name": "Keys in ascending month order", "expr": "list(monthly_totals([{'date': '2025-02-10', 'amount': 1.0}, {'date': '2024-12-31', 'amount': 2.0}, {'date': '2025-01-01', 'amount': 3.0}]))", "expect": "['2024-12', '2025-01', '2025-02']" }
    ],
    "approach": [
      "The month key is the first 7 characters of the date: date[:7].",
      "Create the key even for voided transactions (setdefault), so an all-voided month still appears with 0.0. Only add when the amount isn't None.",
      "Round at the end, not on each addition, so rounding errors don't pile up.",
      "Dicts keep insertion order, so build the final dict from sorted(keys) to control the order."
    ],
    "mistakes": [
      "Skipping voided transactions entirely, so an all-voided month never appears.",
      "total += None, which raises TypeError.",
      "Returning 0.30000000000000004 because the total was never rounded.",
      "Returning keys in input order instead of month order."
    ]
  },
  {
    "id": "py-transfer-exceptions",
    "section": "python",
    "type": "python",
    "topic": "Exceptions: custom hierarchy, raising and catching",
    "title": "Transfers that fail safely",
    "prompt": [
      "Define an exception hierarchy:",
      "- `TransferError`, a subclass of `Exception`",
      "- `UnknownAccountError` and `InsufficientBalanceError`, both subclasses of `TransferError`",
      "",
      "Write `transfer(balances, src, dst, amount)`. `balances` is a dict of account name to balance. Move `amount` from `src` to `dst` by updating the dict. Check in this order and raise the first problem you find, leaving `balances` unchanged:",
      "1. `amount <= 0`: raise `ValueError`",
      "2. `src` or `dst` is not in `balances`: raise `UnknownAccountError`",
      "3. `balances[src] < amount`: raise `InsufficientBalanceError` (moving the entire balance is allowed)",
      "",
      "Write `run_batch(balances, transfers)`. `transfers` is a list of `(src, dst, amount)` tuples. Apply them in order. Skip any transfer that raises a `TransferError` and keep going. Return the number of skipped transfers. A `ValueError` means the batch itself is broken: do not catch it."
    ],
    "starter": [
      "class TransferError(Exception):",
      "    pass",
      "",
      "",
      "class UnknownAccountError(TransferError):",
      "    pass",
      "",
      "",
      "class InsufficientBalanceError(TransferError):",
      "    pass",
      "",
      "",
      "def transfer(balances, src, dst, amount):",
      "    pass",
      "",
      "",
      "def run_batch(balances, transfers):",
      "    pass",
      ""
    ],
    "solution": [
      "class TransferError(Exception):",
      "    pass",
      "",
      "",
      "class UnknownAccountError(TransferError):",
      "    pass",
      "",
      "",
      "class InsufficientBalanceError(TransferError):",
      "    pass",
      "",
      "",
      "def transfer(balances, src, dst, amount):",
      "    if amount <= 0:",
      "        raise ValueError(f'Amount must be positive, got {amount}')",
      "    for name in (src, dst):",
      "        if name not in balances:",
      "            raise UnknownAccountError(name)",
      "    if balances[src] < amount:",
      "        raise InsufficientBalanceError(f'{src} has {balances[src]}, needs {amount}')",
      "    balances[src] -= amount",
      "    balances[dst] += amount",
      "",
      "",
      "def run_batch(balances, transfers):",
      "    skipped = 0",
      "    for src, dst, amount in transfers:",
      "        try:",
      "            transfer(balances, src, dst, amount)",
      "        except TransferError:",
      "            skipped += 1",
      "    return skipped",
      ""
    ],
    "tests": [
      { "name": "Money moves between accounts", "setup": "b = {'A': 100, 'B': 0}\ntransfer(b, 'A', 'B', 40)", "expr": "b", "expect": "{'A': 60, 'B': 40}" },
      { "name": "Moving the whole balance is allowed", "setup": "b = {'A': 100, 'B': 0}\ntransfer(b, 'A', 'B', 100)", "expr": "b", "expect": "{'A': 0, 'B': 100}" },
      { "name": "Unknown account raises UnknownAccountError", "setup": "b = {'A': 100}", "expr": "transfer(b, 'A', 'Z', 10)", "raises": "UnknownAccountError" },
      { "name": "Insufficient balance raises and changes nothing", "setup": "b = {'A': 50, 'B': 0}\ntry:\n    transfer(b, 'A', 'B', 60)\n    raised = False\nexcept InsufficientBalanceError:\n    raised = True", "expr": "(raised, b)", "expect": "(True, {'A': 50, 'B': 0})" },
      { "name": "Batch skips failures and applies the rest", "setup": "b = {'A': 100, 'B': 50}\nn = run_batch(b, [('A', 'B', 30), ('B', 'Z', 5), ('B', 'A', 500), ('B', 'A', 80)])", "expr": "(n, b)", "expect": "(2, {'A': 150, 'B': 0})" },
      { "name": "Batch does not swallow ValueError", "expr": "run_batch({'A': 10, 'B': 0}, [('A', 'B', 0)])", "raises": "ValueError" }
    ],
    "approach": [
      "Build the hierarchy with empty class bodies: class UnknownAccountError(TransferError): pass. Catching TransferError then also catches both subclasses.",
      "Check every condition before touching the dict, in the order given, so a failed transfer changes nothing.",
      "In run_batch, catch the narrowest exception that should be skipped (TransferError), never a bare except or Exception, so the ValueError still propagates.",
      "Walk through the batch test by hand: after the first transfer A=70, B=80; the second fails (unknown Z); the third fails (80 < 500); the fourth leaves B=0, A=150."
    ],
    "mistakes": [
      "except Exception: in run_batch, which also swallows the ValueError the last test expects.",
      "Checking the balance before the account names, so a transfer to an unknown account can still raise KeyError instead of UnknownAccountError.",
      "Subtracting from src before checking dst exists, so a failed transfer still changes the balance.",
      "Using <= in the balance check, which blocks moving the whole balance.",
      "Making UnknownAccountError subclass Exception directly, so except TransferError doesn't catch it."
    ]
  },
  {
    "id": "py-normalize-names",
    "section": "python",
    "type": "python",
    "topic": "String manipulation and de-duplication",
    "title": "Normalize customer names",
    "prompt": [
      "Customer names were typed in by hand. Write `normalize_names(names)` that cleans a list of raw names:",
      "",
      "- Skip entries that are `None` or contain only whitespace.",
      "- Split each name on whitespace and join the words with single spaces.",
      "- In each word, upper-case the first character and lower-case all the others (so `MARY-ANNE` becomes `Mary-anne`).",
      "- Remove duplicates, keeping the first occurrence, comparing the cleaned names.",
      "",
      "Return the cleaned names in their original order. An empty list returns `[]`."
    ],
    "starter": [
      "def normalize_names(names):",
      "    pass",
      ""
    ],
    "solution": [
      "def normalize_names(names):",
      "    seen = set()",
      "    cleaned = []",
      "    for raw in names:",
      "        if raw is None:",
      "            continue",
      "        words = raw.split()",
      "        if not words:",
      "            continue",
      "        name = ' '.join(w[:1].upper() + w[1:].lower() for w in words)",
      "        if name not in seen:",
      "            seen.add(name)",
      "            cleaned.append(name)",
      "    return cleaned",
      ""
    ],
    "tests": [
      { "name": "Case and extra spaces", "expr": "normalize_names(['  ana   CHEN '])", "expect": "['Ana Chen']" },
      { "name": "Only the first letter of each word is capitalized", "expr": "normalize_names([\"MARY-ANNE o'brien\"])", "expect": "[\"Mary-anne O'brien\"]" },
      { "name": "None and blank entries are skipped", "expr": "normalize_names([None, '   ', 'bo li'])", "expect": "['Bo Li']" },
      { "name": "Duplicates removed, first one kept", "expr": "normalize_names(['bo li', 'Ana Chen', 'BO  LI'])", "expect": "['Bo Li', 'Ana Chen']" },
      { "name": "Empty list", "expr": "normalize_names([])", "expect": "[]" },
      { "name": "Order is preserved", "expr": "normalize_names(['zed', 'amy', 'mo'])", "expect": "['Zed', 'Amy', 'Mo']" }
    ],
    "approach": [
      "str.split() with no argument splits on any run of whitespace and drops leading and trailing spaces, so ' '.join(s.split()) collapses spacing in one step.",
      "Follow the capitalization rule exactly: word[:1].upper() + word[1:].lower(). str.title() and str.capitalize() on the whole string do something different.",
      "Use a set for what you've already kept, and a list for the output, so order is preserved and lookups are fast.",
      "Filter None before calling any string method on the value."
    ],
    "mistakes": [
      "Using str.title(), which capitalizes after hyphens and apostrophes too ('Mary-Anne O'Brien'), contradicting the stated rule.",
      "Calling .split() on None, which raises AttributeError.",
      "De-duplicating with set(names) or a dict without care, which loses the original order.",
      "Comparing raw strings for duplicates, so 'bo li' and 'BO  LI' both survive."
    ]
  },
  {
    "id": "py-transaction-alerts",
    "section": "python",
    "type": "python",
    "topic": "Conditionals and printed output (HackerRank style)",
    "title": "Transaction alerts",
    "prompt": [
      "You are given a list of transaction amounts (whole dollars). For each amount, in order, print one line:",
      "",
      "- `REFUND` if the amount is negative",
      "- `FRAUD CHECK` if the amount is at least 5000 and is a multiple of 1000",
      "- `LARGE` if the amount is at least 5000 otherwise",
      "- `OK` for everything else, including 0",
      "",
      "Complete the function `transactionAlerts`. It prints its results; it does not return anything. If there are no transactions, print nothing.",
      "",
      "**Input format:** the first line is n, the number of transactions. Each of the next n lines holds one integer amount. The code that reads the input is already written for you."
    ],
    "starter": [
      "#!/bin/python3",
      "",
      "import math",
      "import os",
      "import random",
      "import re",
      "import sys",
      "",
      "#",
      "# Complete the 'transactionAlerts' function below.",
      "#",
      "# The function accepts INTEGER_ARRAY amounts as parameter.",
      "#",
      "",
      "def transactionAlerts(amounts):",
      "    # Write your code here",
      "",
      "if __name__ == '__main__':",
      "    amounts_count = int(input().strip())",
      "",
      "    amounts = []",
      "",
      "    for _ in range(amounts_count):",
      "        amounts_item = int(input().strip())",
      "        amounts.append(amounts_item)",
      "",
      "    transactionAlerts(amounts)",
      ""
    ],
    "solution": [
      "#!/bin/python3",
      "",
      "import math",
      "import os",
      "import random",
      "import re",
      "import sys",
      "",
      "",
      "def transactionAlerts(amounts):",
      "    for amount in amounts:",
      "        if amount < 0:",
      "            print('REFUND')",
      "        elif amount >= 5000 and amount % 1000 == 0:",
      "            print('FRAUD CHECK')",
      "        elif amount >= 5000:",
      "            print('LARGE')",
      "        else:",
      "            print('OK')",
      "",
      "if __name__ == '__main__':",
      "    amounts_count = int(input().strip())",
      "",
      "    amounts = []",
      "",
      "    for _ in range(amounts_count):",
      "        amounts_item = int(input().strip())",
      "        amounts.append(amounts_item)",
      "",
      "    transactionAlerts(amounts)",
      ""
    ],
    "tests": [
      { "name": "Sample case 0", "stdin": "5\n120\n5000\n7350\n-40\n0\n", "stdout": "OK\nFRAUD CHECK\nLARGE\nREFUND\nOK\n" },
      { "name": "Just around 5000", "stdin": "3\n4999\n5001\n10000\n", "stdout": "OK\nLARGE\nFRAUD CHECK\n" },
      { "name": "No transactions", "stdin": "0\n", "stdout": "" },
      { "name": "Negative multiple of 1000 is a refund", "stdin": "2\n-5000\n1000\n", "stdout": "REFUND\nOK\n" },
      { "name": "Single round amount", "stdin": "1\n6000\n", "stdout": "FRAUD CHECK\n" },
      { "name": "Mixed small amounts", "stdin": "4\n999\n1000\n-1\n5500\n", "stdout": "OK\nOK\nREFUND\nLARGE\n" }
    ],
    "approach": [
      "This is FizzBuzz with a banking theme: an if/elif chain where the order of the checks matters.",
      "Put the most specific rule first. Negative amounts come before the \"at least 5000\" rules, and FRAUD CHECK (a special case of large) comes before LARGE.",
      "Print exactly the words asked for, one per line, with nothing else. HackerRank compares your printed output line by line.",
      "Don't edit the input code under __main__, and don't print anything extra (such as debugging text) in your final answer."
    ],
    "mistakes": [
      "Checking LARGE before FRAUD CHECK, so 5000 and 10000 print LARGE.",
      "Writing amount > 5000, which misses exactly 5000.",
      "Letting -5000 fall into FRAUD CHECK because -5000 % 1000 == 0, by testing the multiple before the sign.",
      "Returning a list instead of printing, or calling print(transactionAlerts(amounts)), which adds a line saying None.",
      "Leaving the stub's \"# Write your code here\" with no code under it: Python raises IndentationError."
    ]
  },
  {
    "id": "py-most-active-account",
    "section": "python",
    "type": "python",
    "topic": "Parsing input, dictionaries and tie-breaks (HackerRank style)",
    "title": "Most active account",
    "prompt": [
      "Each transaction is a string with an account ID and an amount separated by a space, for example `A12 -250`. An account's **activity** is the sum of the absolute values of its amounts (so deposits and withdrawals both count).",
      "",
      "Complete `mostActiveAccount`, which returns the ID of the account with the highest activity. If several accounts tie, return the one whose ID comes first alphabetically (plain string comparison).",
      "",
      "**Input format:** the first line is n (n ≥ 1). Each of the next n lines is one transaction. The code that reads the input and writes your returned value is already written."
    ],
    "starter": [
      "#!/bin/python3",
      "",
      "import math",
      "import os",
      "import random",
      "import re",
      "import sys",
      "",
      "#",
      "# Complete the 'mostActiveAccount' function below.",
      "#",
      "# The function is expected to return a STRING.",
      "# The function accepts STRING_ARRAY transactions as parameter.",
      "#",
      "",
      "def mostActiveAccount(transactions):",
      "    # Write your code here",
      "",
      "if __name__ == '__main__':",
      "    fptr = open(os.environ['OUTPUT_PATH'], 'w')",
      "",
      "    transactions_count = int(input().strip())",
      "",
      "    transactions = []",
      "",
      "    for _ in range(transactions_count):",
      "        transactions_item = input()",
      "        transactions.append(transactions_item)",
      "",
      "    result = mostActiveAccount(transactions)",
      "",
      "    fptr.write(result + '\\n')",
      "",
      "    fptr.close()",
      ""
    ],
    "solution": [
      "#!/bin/python3",
      "",
      "import math",
      "import os",
      "import random",
      "import re",
      "import sys",
      "",
      "",
      "def mostActiveAccount(transactions):",
      "    activity = {}",
      "    for line in transactions:",
      "        account, amount = line.split()",
      "        activity[account] = activity.get(account, 0) + abs(int(amount))",
      "    return min(activity, key=lambda a: (-activity[a], a))",
      "",
      "if __name__ == '__main__':",
      "    fptr = open(os.environ['OUTPUT_PATH'], 'w')",
      "",
      "    transactions_count = int(input().strip())",
      "",
      "    transactions = []",
      "",
      "    for _ in range(transactions_count):",
      "        transactions_item = input()",
      "        transactions.append(transactions_item)",
      "",
      "    result = mostActiveAccount(transactions)",
      "",
      "    fptr.write(result + '\\n')",
      "",
      "    fptr.close()",
      ""
    ],
    "tests": [
      { "name": "Sample case 0", "stdin": "4\nA12 100\nB07 -250\nA12 120\nC33 50\n", "stdout": "B07\n" },
      { "name": "Tie goes to the first ID alphabetically", "stdin": "2\nZ1 300\nA9 -300\n", "stdout": "A9\n" },
      { "name": "One transaction of zero", "stdin": "1\nQ5 0\n", "stdout": "Q5\n" },
      { "name": "Withdrawals count toward activity", "stdin": "5\nX1 10\nX2 20\nX1 -15\nX2 -5\nX3 24\n", "stdout": "X1\n" },
      { "name": "Totals across several lines", "stdin": "3\nM1 1000\nM2 999\nM2 2\n", "stdout": "M2\n" },
      { "name": "String order, not numeric order", "stdin": "3\nacc10 5\nacc9 5\nacc10 0\n", "stdout": "acc10\n" }
    ],
    "approach": [
      "Parse each line with split(): the first part is the ID, the second converts with int().",
      "Accumulate activity per account in a dict with abs() so withdrawals add, not subtract.",
      "Pick the winner with one key that encodes both rules: highest activity first, then alphabetical ID. min(d, key=lambda a: (-d[a], a)) does both.",
      "Return the string; the provided code writes it to the output file. If you print it instead, HackerRank shows it as debug output and the test still fails."
    ],
    "mistakes": [
      "Adding the signed amounts, so a withdrawal lowers activity: B07 would total -250 and lose.",
      "Using max(d, key=d.get), which breaks ties by dictionary order instead of alphabetically.",
      "Comparing IDs as numbers, or assuming 'acc9' sorts before 'acc10'. In string order, '1' comes before '9'.",
      "Printing the result instead of returning it."
    ]
  },
  {
    "id": "py-print-statement",
    "section": "python",
    "type": "python",
    "topic": "String formatting and exact output (HackerRank style)",
    "title": "Print an account statement",
    "prompt": [
      "Print an account statement. You are given a starting balance and a list of transactions, each a date and an amount. For each transaction, in order, update the balance and print one line:",
      "",
      "`DATE AMOUNT BALANCE`",
      "",
      "- AMOUNT always shows its sign and 2 decimals, like `+50.00` or `-30.50`.",
      "- BALANCE shows 2 decimals and a minus sign only if it's negative, like `119.50` or `-80.50`.",
      "- If the new balance is below zero, add ` OVERDRAWN` at the end of that line. A balance of exactly 0 is not overdrawn.",
      "",
      "If there are no transactions, print `No transactions` instead.",
      "",
      "**Input format:** the first line is the starting balance. The second line is n. Each of the next n lines is a date and an amount separated by a space. The input code is already written."
    ],
    "starter": [
      "#!/bin/python3",
      "",
      "import math",
      "import os",
      "import random",
      "import re",
      "import sys",
      "",
      "#",
      "# Complete the 'printStatement' function below.",
      "#",
      "# The function accepts following parameters:",
      "#  1. FLOAT start",
      "#  2. LIST transactions of (STRING date, FLOAT amount) pairs",
      "#",
      "",
      "def printStatement(start, transactions):",
      "    # Write your code here",
      "",
      "if __name__ == '__main__':",
      "    start = float(input().strip())",
      "",
      "    n = int(input().strip())",
      "",
      "    transactions = []",
      "",
      "    for _ in range(n):",
      "        date, amount = input().split()",
      "        transactions.append((date, float(amount)))",
      "",
      "    printStatement(start, transactions)",
      ""
    ],
    "solution": [
      "#!/bin/python3",
      "",
      "import math",
      "import os",
      "import random",
      "import re",
      "import sys",
      "",
      "",
      "def printStatement(start, transactions):",
      "    if not transactions:",
      "        print('No transactions')",
      "        return",
      "    balance = start",
      "    for date, amount in transactions:",
      "        balance += amount",
      "        line = f'{date} {amount:+.2f} {balance:.2f}'",
      "        if balance < 0:",
      "            line += ' OVERDRAWN'",
      "        print(line)",
      "",
      "if __name__ == '__main__':",
      "    start = float(input().strip())",
      "",
      "    n = int(input().strip())",
      "",
      "    transactions = []",
      "",
      "    for _ in range(n):",
      "        date, amount = input().split()",
      "        transactions.append((date, float(amount)))",
      "",
      "    printStatement(start, transactions)",
      ""
    ],
    "tests": [
      { "name": "Sample case 0", "stdin": "100\n3\n2025-01-03 50\n2025-01-04 -30.5\n2025-01-09 -200\n", "stdout": "2025-01-03 +50.00 150.00\n2025-01-04 -30.50 119.50\n2025-01-09 -200.00 -80.50 OVERDRAWN\n" },
      { "name": "No transactions", "stdin": "0\n0\n", "stdout": "No transactions\n" },
      { "name": "Exactly zero is not overdrawn", "stdin": "20\n1\n2025-02-01 -20\n", "stdout": "2025-02-01 -20.00 0.00\n" },
      { "name": "Starting below zero", "stdin": "-10\n1\n2025-03-01 5\n", "stdout": "2025-03-01 +5.00 -5.00 OVERDRAWN\n" },
      { "name": "Decimals are rounded for display", "stdin": "0.1\n1\n2025-04-01 0.2\n", "stdout": "2025-04-01 +0.20 0.30\n" },
      { "name": "A zero amount still shows a sign", "stdin": "50\n1\n2025-05-05 0\n", "stdout": "2025-05-05 +0.00 50.00\n" }
    ],
    "approach": [
      "Handle the empty case first and return early.",
      "Keep a running balance and format each line with an f-string: {amount:+.2f} forces a sign, {balance:.2f} gives 2 decimals.",
      "Compare the unrounded balance with 0 for the OVERDRAWN rule, and use < so exactly 0 isn't flagged.",
      "Output format is the whole question here: single spaces, no extra text, one line per transaction."
    ],
    "mistakes": [
      "Using {amount:.2f}, which drops the plus sign on deposits.",
      "Printing round(balance, 2), which shows 150.0 instead of 150.00.",
      "Using <= 0 for OVERDRAWN, which flags a zero balance.",
      "Printing nothing (instead of No transactions) when n is 0.",
      "Adding extra spaces or labels, which fail a line-by-line comparison."
    ]
  }
]
);
